name: "prompt-test"
on:
  pull_request:
    paths:
      - ".github/workflows/prompt-test.yml"
      - "frontend/packages/jobs/**"
      - "frontend/packages/prompt-test/**"

jobs:
  eval:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ./.github/actions/pnpm-setup

      - name: Run pnpm test:prompt
        env:
          OPENAI_API_KEY: ${{ secrets.PROMPT_TEST_OPENAI_API_KEY }}
          LANGFUSE_PUBLIC_KEY: ${{ secrets.PROMPT_TEST_LANGFUSE_PUBLIC_KEY }}
          LANGFUSE_SECRET_KEY: ${{ secrets.PROMPT_TEST_LANGFUSE_SECRET_KEY }}
        id: pnpm-test-prompt
        shell: bash
        # TODO: fail when there are errors or failures
        # TODO: Consider using turborepo passthrough variables.
        run: |
          # see https://turbo.build/docs/crafting-your-repository/using-environment-variables#passthrough-variables
          echo "OPENAI_API_KEY=${OPENAI_API_KEY}" > .env.local
          echo "LANGFUSE_PUBLIC_KEY=${LANGFUSE_PUBLIC_KEY}" >> .env
          echo "LANGFUSE_SECRET_KEY=${LANGFUSE_SECRET_KEY}" >> .env

          # TODO: fail when there are errors or failures
          pnpm test:prompt || (echo 'failed' ; exit 0)

          rm -f .env .env.local

          url=$(cat frontend/packages/prompt-test/result.json | jq -r .url)
          echo "url=$url" >> $GITHUB_OUTPUT

          datasetRunItemsLength=$(cat frontend/packages/prompt-test/result.json | jq -r .datasetRunItemsLength)
          echo "datasetRunItemsLength=$datasetRunItemsLength" >> $GITHUB_OUTPUT

          testByJsGoodCount=$(cat frontend/packages/prompt-test/result.json | jq -r .testByJsGoodCount)
          echo "testByJsGoodCount=$testByJsGoodCount" >> $GITHUB_OUTPUT

          testByJsBadCount=$(cat frontend/packages/prompt-test/result.json | jq -r .testByJsBadCount)
          echo "testByJsBadCount=$testByJsBadCount" >> $GITHUB_OUTPUT

          testByLlmGoodCount=$(cat frontend/packages/prompt-test/result.json | jq -r .testByLlmGoodCount)
          echo "testByLlmGoodCount=$testByLlmGoodCount" >> $GITHUB_OUTPUT

          testByLlmBadCount=$(cat frontend/packages/prompt-test/result.json | jq -r .testByLlmBadCount)
          echo "testByLlmBadCount=$testByLlmBadCount" >> $GITHUB_OUTPUT

      - name: Post result
        if: always()
        uses: marocchino/sticky-pull-request-comment@67d0dec7b07ed060a405f9b2a64b8ab319fdd7db # v2.9.2
        with:
          message: |
            frontend/packages/prompt-test result:

            visit: ${{steps.pnpm-test-prompt.outputs.url}}

            | run items length |
            | --- |
            | ${{steps.pnpm-test-prompt.outputs.datasetRunItemsLength}} |

            | score | pass(&gt;=1) ✅ | failed(&lt;1) ❌️ |
            | ---  | ---: | ---: |
            | test-by-js | ${{steps.pnpm-test-prompt.outputs.testByJsGoodCount}} | ${{steps.pnpm-test-prompt.outputs.testByJsBadCount}} |
            | test-by-llm | ${{steps.pnpm-test-prompt.outputs.testByLlmGoodCount}} | ${{steps.pnpm-test-prompt.outputs.testByLlmBadCount}} |
